"""
Crop Knowledge Base — Punjab-specific profiles
Covers Kharif, Rabi, and Zaid seasons for all 3 Punjab soil zones
"""

CROP_PROFILES = {
    # ── KHARIF crops ──────────────────────────────────────────────
    "rice": {
        "name": "Rice",
        "local_name_hi": "चावल",
        "local_name_pa": "ਚੌਲ",
        "season": ["kharif"],
        "soil_types": ["loamy", "clay", "alluvial"],
        "water_req": "high",
        "duration_days": 130,
        "msp_per_quintal": 2300.0,
        "input_cost_per_acre": 15000.0,
        "expected_yield_qtl_per_acre": 28.0,
        "soil_zones": ["majha", "malwa", "doaba"],
        "stubble_friendly": False,          # major stubble burning concern
        "stubble_warning": "Rice stubble burning causes severe air pollution in Punjab. Consider alternatives.",
        "advice": "Transplant in June-July. Use SRI method to save 30% water.",
    },
    "maize": {
        "name": "Maize",
        "local_name_hi": "मक्का",
        "local_name_pa": "ਮੱਕੀ",
        "season": ["kharif"],
        "soil_types": ["loamy", "sandy-loam", "alluvial"],
        "water_req": "medium",
        "duration_days": 95,
        "msp_per_quintal": 2090.0,
        "input_cost_per_acre": 8000.0,
        "expected_yield_qtl_per_acre": 22.0,
        "soil_zones": ["majha", "malwa", "doaba"],
        "stubble_friendly": True,
        "stubble_warning": None,
        "advice": "Excellent rice alternative. Reduces stubble burning. Sow June 1–15.",
    },
    "cotton": {
        "name": "Cotton",
        "local_name_hi": "कपास",
        "local_name_pa": "ਕਪਾਹ",
        "season": ["kharif"],
        "soil_types": ["loamy", "sandy-loam"],
        "water_req": "medium",
        "duration_days": 180,
        "msp_per_quintal": 7020.0,
        "input_cost_per_acre": 20000.0,
        "expected_yield_qtl_per_acre": 8.0,
        "soil_zones": ["malwa"],
        "stubble_friendly": True,
        "stubble_warning": None,
        "advice": "Malwa zone specialty. Monitor pink bollworm from September.",
    },
    "groundnut": {
        "name": "Groundnut",
        "local_name_hi": "मूँगफली",
        "local_name_pa": "ਮੂੰਗਫਲੀ",
        "season": ["kharif"],
        "soil_types": ["sandy-loam"],
        "water_req": "low",
        "duration_days": 110,
        "msp_per_quintal": 6377.0,
        "input_cost_per_acre": 10000.0,
        "expected_yield_qtl_per_acre": 10.0,
        "soil_zones": ["malwa"],
        "stubble_friendly": True,
        "stubble_warning": None,
        "advice": "Best for sandy Malwa soils. Low water requirement suits limited irrigation.",
    },
    "moong": {
        "name": "Moong (Green Gram)",
        "local_name_hi": "मूंग",
        "local_name_pa": "ਮੂੰਗ",
        "season": ["kharif", "zaid"],
        "soil_types": ["loamy", "sandy-loam", "alluvial"],
        "water_req": "low",
        "duration_days": 60,
        "msp_per_quintal": 8558.0,
        "input_cost_per_acre": 5000.0,
        "expected_yield_qtl_per_acre": 5.0,
        "soil_zones": ["majha", "malwa", "doaba"],
        "stubble_friendly": True,
        "stubble_warning": None,
        "advice": "Short-duration legume. Fixes nitrogen, ideal before wheat. Reduces input cost.",
    },

    # ── RABI crops ────────────────────────────────────────────────
    "wheat": {
        "name": "Wheat",
        "local_name_hi": "गेहूं",
        "local_name_pa": "ਕਣਕ",
        "season": ["rabi"],
        "soil_types": ["loamy", "clay", "alluvial", "sandy-loam"],
        "water_req": "medium",
        "duration_days": 150,
        "msp_per_quintal": 2275.0,
        "input_cost_per_acre": 12000.0,
        "expected_yield_qtl_per_acre": 20.0,
        "soil_zones": ["majha", "malwa", "doaba"],
        "stubble_friendly": True,
        "stubble_warning": None,
        "advice": "Sow Nov 1–15. Use HD-3086 or PBW-723 varieties for Punjab conditions.",
    },
    "mustard": {
        "name": "Mustard",
        "local_name_hi": "सरसों",
        "local_name_pa": "ਸਰ੍ਹੋਂ",
        "season": ["rabi"],
        "soil_types": ["sandy-loam", "loamy"],
        "water_req": "low",
        "duration_days": 120,
        "msp_per_quintal": 5650.0,
        "input_cost_per_acre": 6000.0,
        "expected_yield_qtl_per_acre": 7.0,
        "soil_zones": ["malwa", "majha"],
        "stubble_friendly": True,
        "stubble_warning": None,
        "advice": "Low water oilseed crop. Sow Oct 15 – Nov 1. Good for water-scarce areas.",
    },
    "potato": {
        "name": "Potato",
        "local_name_hi": "आलू",
        "local_name_pa": "ਆਲੂ",
        "season": ["rabi"],
        "soil_types": ["loamy", "sandy-loam", "alluvial"],
        "water_req": "medium",
        "duration_days": 90,
        "msp_per_quintal": None,  # market-linked
        "input_cost_per_acre": 50000.0,
        "expected_yield_qtl_per_acre": 100.0,
        "soil_zones": ["doaba", "majha"],
        "stubble_friendly": True,
        "stubble_warning": None,
        "advice": "High value crop. Doaba & Majha zones best. Plant Oct–Nov.",
    },
    "sunflower": {
        "name": "Sunflower",
        "local_name_hi": "सूरजमुखी",
        "local_name_pa": "ਸੂਰਜਮੁਖੀ",
        "season": ["rabi", "zaid"],
        "soil_types": ["loamy", "sandy-loam"],
        "water_req": "low",
        "duration_days": 100,
        "msp_per_quintal": 6760.0,
        "input_cost_per_acre": 7000.0,
        "expected_yield_qtl_per_acre": 6.0,
        "soil_zones": ["majha", "malwa"],
        "stubble_friendly": True,
        "stubble_warning": None,
        "advice": "Drought-tolerant oilseed. Good alternative for water-scarce fields.",
    },

    # ── ZAID / vegetables ─────────────────────────────────────────
    "vegetables_mixed": {
        "name": "Seasonal Vegetables",
        "local_name_hi": "सब्जियां",
        "local_name_pa": "ਸਬਜ਼ੀਆਂ",
        "season": ["kharif", "rabi", "zaid"],
        "soil_types": ["loamy", "sandy-loam", "alluvial"],
        "water_req": "medium",
        "duration_days": 60,
        "msp_per_quintal": None,
        "input_cost_per_acre": 25000.0,
        "expected_yield_qtl_per_acre": 80.0,
        "soil_zones": ["majha", "malwa", "doaba"],
        "stubble_friendly": True,
        "stubble_warning": None,
        "advice": "High-margin option. Best for small landholdings. Tomato, pea, cauliflower recommended.",
    },
}

# Punjab free electricity irrigation windows (tube-well feeder schedule)
ELECTRICITY_SLOTS = {
    "morning": {"start": "05:00", "end": "08:00", "label": "Morning slot"},
    "night": {"start": "22:00", "end": "01:00", "label": "Night slot"},
}

# District to soil zone mapping
DISTRICT_ZONE_MAP = {
    # Majha zone
    "amritsar": "majha", "gurdaspur": "majha", "pathankot": "majha",
    "tarn taran": "majha",
    # Malwa zone
    "ludhiana": "malwa", "bathinda": "malwa", "mansa": "malwa",
    "muktsar": "malwa", "faridkot": "malwa", "ferozepur": "malwa",
    "moga": "malwa", "barnala": "malwa", "sangrur": "malwa",
    "patiala": "malwa", "fatehgarh sahib": "malwa",
    # Doaba zone
    "jalandhar": "doaba", "hoshiarpur": "doaba", "nawanshahr": "doaba",
    "kapurthala": "doaba",
}
